# Intro to Numpy Exercises

Natasha Watkins

### Problem 1

In [1]:
import numpy as np

A = np.array([[3, -1, 4], 
              [1, 5, -9]])

B = np.array([[2, 6, -5, 3], 
              [5, -8, 9, 7], 
              [9, -3, -2, 3]])

In [2]:
A @ B

array([[ 37,  14, -32,  14],
       [-54,  -7,  58,  11]])

### Problem 2

In [3]:
def compute_matrix():
    A = np.array([[3, 1, 4], 
                  [1, 5, 9], 
                  [-5, 3, 1]])
    return -np.linalg.matrix_power(A, 3) + 9 * np.linalg.matrix_power(A, 2) - 15 * A

In [4]:
compute_matrix()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Problem 3

In [5]:
def ABA():
    n = 7
    matrix = np.ones((n, n))
    A = 0 * np.tril(matrix, k=-1) + np.triu(matrix)
    B = -1 * np.tril(matrix) + 5 * np.triu(matrix, k=1)
    return (A @ B @ A).astype(np.int64)

In [6]:
ABA()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

### Problem 4

In [7]:
def fancy_index(a):
    b = np.copy(a)
    b[b < 0] = 0
    return b

In [8]:
fancy_index(A)

array([[3, 0, 4],
       [1, 5, 0]])

### Problem 5

In [9]:
def block_matrix():
    A = np.array([[0, 2, 4], [1, 3, 5]])
    B = 3 * np.tril(np.ones((3, 3)))
    C = -2 * np.eye(3)
    eye = np.eye(3)
    return np.vstack((np.hstack((np.zeros((3, 4)), A.T, eye)), 
                      np.hstack((A, np.zeros_like(A), np.zeros_like(A))),
                      np.hstack((B, np.zeros_like(B), C))))

In [10]:
block_matrix()

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0.,  0., -0., -0., -2.]])

### Problem 6

In [32]:
def row_stochastic(A):
     return A / A.sum(axis=1).reshape(A.shape[0], 1)

In [33]:
row_stochastic(A)

array([[ 0.5       , -0.16666667,  0.66666667],
       [-0.33333333, -1.66666667,  3.        ]])

### Problem 7

In [34]:
grid = np.load("grid.npy")

In [64]:
def greatest_4(grid):
    h_max = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    v_max = np.max(grid[:-3, :] * grid[1:-2, :] * grid[2:-1, :] * grid[3:, :])
    r_max = np.max(grid[:-3, :-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    l_max = np.max(grid[:-3, 3:] * grid[1:-2, 2:-1] * grid[2:-1, 1:-2] * grid[3:, :-3])
    return max(h_max, v_max, r_max, l_max)

In [65]:
greatest_4(grid)

70600674

# The Standard Library Exercises

### Problem 1

In [209]:
def min_max_avg(list):
    return min(list), max(list), sum(list)/len(list)

In [210]:
min_max_avg([3, 4, 6])

(3, 6, 4.333333333333333)

### Problem 2

In [213]:
int_1 = 1
int_2 = int_1
int_2 = 3
int_1 == int_2

False

In [214]:
str_1 = 'hi'
str_2 = str_1
str_2 = 'hello'
str_1 == str_2

False

In [215]:
list_1 = [1, 2]
list_2 = list_1
list_2[0] = 2
list_1 == list_2

True

In [219]:
tuple_1 = (1, 2)
tuple_2 = tuple_1
tuple_2 += (1,)
tuple_1 == tuple_2

False

In [229]:
set_1 = set((1, 2, 3))
set_2 = set_1
set_2.add(4)
set_1 == set_2

True

### Problem 3

In [67]:
from calculator import *

In [68]:
def triangle(a, b):
    return sqrt(add_ab(a**2, b**2))

In [69]:
triangle(3, 4)

5.0

### Problem 4

In [353]:
from itertools import combinations, chain

def power_set(A):
    r = len(A)
    sets = {}
    for i in range(r+1):
        set_i = (list(combinations(A, r=i)))
        sets.append([set(list(item)) for item in set_i])
    return list(chain.from_iterable(sets))

In [356]:
power_set([1, 2, 3])

[set(), {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}]