# Econ Probset4

Natasha Watkins

In [1]:
import numpy as np
from scipy.optimize import root

## Exercise 5

The steady-state when evaluated at $\bar{z} = 0$ is given by
$$
\bar{k} = \Big[\frac{(1 - \beta)}{\alpha \beta (1 - \tau)} + \frac{\delta}{\alpha}\Big]^\frac{1}{\alpha-1}
$$

In [2]:
# Parameters
γ = 2.5
β = 0.98
α = 0.4
δ = 0.1
z = 0
τ = 0.05

**Algebraic solutions**

Steady-state capital

In [3]:
frac1 = (1 - β) / (α * β * (1 - τ))
frac2 = δ / α
k_bar = (frac1 + frac2)**(1/(α-1))
k_bar

7.287497950692988

Steady-state output

In [4]:
y_bar = k_bar**α
y_bar

2.213254613918843

Steady-state investment

In [5]:
i_bar = δ * k_bar
i_bar

0.7287497950692988

**Numerical solutions**

Steady-state capital

In [6]:
def solve_ss(k, γ, β, α, δ, z, τ):
    r = α * k**(α - 1) * (np.exp(z))**(1 - α)
    return β * ((r - δ) * (1 - τ) + 1) - 1

In [7]:
k_bar = root(solve_ss, 1, args=(γ, β, α, δ, z, τ)).x
k_bar

array([7.28749795])

In [8]:
k_bar**α

array([2.21325461])

In [9]:
i_bar = δ * k_bar
i_bar

array([0.7287498])

## Exercise 6

In [10]:
# Parameters
γ = 2.5
ξ = 1.5
β = 0.98
α = 0.4
a = 0.5
δ = 0.1
z = 0
τ = 0.05

In [11]:
def solve_ss(params, γ, ξ, β, α, a, δ, z, τ):
    k, l = params
    w = (1 - α) * k**α * (l * np.exp(z))**(1 - α)  # SS wage
    r = α * k**(α - 1) * (l * np.exp(z))**(1 - α)  # SS interest rate
    T = τ * (w * l + (r - δ) * k)
    c = (1 - τ) * (w * (r - δ) * k) + T
    eq1 = β * ((r - δ) * (1 - τ) + 1) - 1
    eq2 = c**(-γ) * w * (1 - τ) - a * (1 - l)**(-ξ)
    return eq1, eq2

Steady-state capital and labour

In [12]:
ss = root(solve_ss, 0.5 * np.ones(2), args=(γ, ξ, β, α, a, δ, z, τ))
k_bar, l_bar, = ss.x
k_bar, l_bar

(6.8991246724247555, 0.9467069108153893)

Steady-state output

In [13]:
y_bar = k_bar**α * l_bar**(1 - α) * np.exp(z)
y_bar

2.0953034383850278

Steady-state investment

In [14]:
i_bar = δ * k_bar
i_bar

0.6899124672424756