# QR Decomposition

In [46]:
from scipy.linalg import norm
import numpy as np
import scipy

### Problem 1

In [343]:
def qr(A):
    m, n = A.shape
    Q = A.copy()
    R = np.zeros((n, n))
    
    for i in range(n):
        R[i, i] = norm(Q[:, i])
        Q[:, i] = Q[:, i] / R[i, i]
        for j in range(i + 1, n):
            R[i, j] = Q[:, j].T @ Q[:, i]
            Q[:, j] = Q[:, j] - R[i, j] * Q[:, i]
            
    return Q, R

In [344]:
A = np.random.random((5, 5))

In [345]:
Q, R = mod_gramschmidt(A)
Q, R

(array([[ 0.43369346,  0.44976826, -0.18146159, -0.4148924 , -0.63604598],
        [ 0.61686085, -0.56233206, -0.14735674,  0.47182441, -0.24276133],
        [ 0.29907386, -0.33835564,  0.71892615, -0.51919787,  0.09822957],
        [ 0.18303336,  0.53814944,  0.59300856,  0.56921039, -0.03513335],
        [ 0.55537941,  0.2782118 , -0.27720701, -0.10807002,  0.72500279]]),
 array([[ 1.57317576,  1.47130205,  0.86631324,  1.58320899,  1.02602758],
        [ 0.        ,  0.38137068,  0.52399991,  0.58511649, -0.21251561],
        [ 0.        ,  0.        ,  0.82195849,  0.10016413, -0.00426562],
        [ 0.        ,  0.        ,  0.        ,  0.23293437, -0.07683629],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.10241293]]))

In [346]:
scipy.linalg.qr(A, mode="economic")

(array([[-0.43369346,  0.44976826,  0.18146159,  0.4148924 , -0.63604598],
        [-0.61686085, -0.56233206,  0.14735674, -0.47182441, -0.24276133],
        [-0.29907386, -0.33835564, -0.71892615,  0.51919787,  0.09822957],
        [-0.18303336,  0.53814944, -0.59300856, -0.56921039, -0.03513335],
        [-0.55537941,  0.2782118 ,  0.27720701,  0.10807002,  0.72500279]]),
 array([[-1.57317576, -1.47130205, -0.86631324, -1.58320899, -1.02602758],
        [ 0.        ,  0.38137068,  0.52399991,  0.58511649, -0.21251561],
        [ 0.        ,  0.        , -0.82195849, -0.10016413,  0.00426562],
        [ 0.        ,  0.        ,  0.        , -0.23293437,  0.07683629],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.10241293]]))

In [347]:
Q.T @ Q

array([[ 1.00000000e+00, -1.79808232e-16,  3.20037482e-17,
        -6.15927329e-16, -2.35061940e-15],
       [-1.79808232e-16,  1.00000000e+00, -2.15726985e-16,
         2.52936837e-16,  3.92889835e-16],
       [ 3.20037482e-17, -2.15726985e-16,  1.00000000e+00,
        -6.84033849e-17,  1.14161779e-17],
       [-6.15927329e-16,  2.52936837e-16, -6.84033849e-17,
         1.00000000e+00,  7.39904686e-17],
       [-2.35061940e-15,  3.92889835e-16,  1.14161779e-17,
         7.39904686e-17,  1.00000000e+00]])

In [348]:
Q @ R

array([[0.68227603, 0.8096225 , 0.46223902, 0.83497556, 0.31691218],
       [0.97043054, 0.69313168, 0.11861166, 0.74273415, 0.69193402],
       [0.47049575, 0.31098907, 0.67272077, 0.22659055, 0.42565044],
       [0.28794365, 0.47453177, 0.9279829 , 0.79664703, 0.02356844],
       [0.87370942, 0.92323269, 0.39906284, 0.98912857, 0.59444606]])

In [349]:
A

array([[0.68227603, 0.8096225 , 0.46223902, 0.83497556, 0.31691218],
       [0.97043054, 0.69313168, 0.11861166, 0.74273415, 0.69193402],
       [0.47049575, 0.31098907, 0.67272077, 0.22659055, 0.42565044],
       [0.28794365, 0.47453177, 0.9279829 , 0.79664703, 0.02356844],
       [0.87370942, 0.92323269, 0.39906284, 0.98912857, 0.59444606]])

### Problem 2

In [350]:
def det(A):
    return np.diag(qr(A)[1]).prod()

In [351]:
det(A)

0.011764211199421207

In [352]:
scipy.linalg.det(A)

-0.01176421119942121

### Problem 3

In [353]:
def solve(A, b):
    Q, R = qr(A)
    n = R.shape[0]
    y = Q.T @ b
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        subtract = 0
        for j in range(i+1, n):
            subtract += R[i, j] * x[j]
        x[i] = (y[i] - subtract) / R[i, i]
        
    return x

In [354]:
A

array([[0.68227603, 0.8096225 , 0.46223902, 0.83497556, 0.31691218],
       [0.97043054, 0.69313168, 0.11861166, 0.74273415, 0.69193402],
       [0.47049575, 0.31098907, 0.67272077, 0.22659055, 0.42565044],
       [0.28794365, 0.47453177, 0.9279829 , 0.79664703, 0.02356844],
       [0.87370942, 0.92323269, 0.39906284, 0.98912857, 0.59444606]])

In [355]:
b = np.ones(5)

In [356]:
solve(A, b)

array([ 1.99694801, -0.30307408,  0.89040931, -0.29699474, -0.88571144])

In [357]:
scipy.linalg.solve(A, b)

array([ 1.99694801, -0.30307408,  0.89040931, -0.29699474, -0.88571144])

### Problem 4

In [372]:
sign = lambda x: 1 if x >= 0 else -1

def householder(A):
    m, n = A.shape
    R = A.copy()
    Q = np.eye(m)
    
    for k in range(n-1):
        u = R[k:, k].copy()
        u[0] = u[0] + sign(u[0]) * norm(u)
        u = u / norm(u)
        R[k:, k:] = R[k:, k:] - 2 * np.outer(u, u.T @ R[k:, k:])
        Q[k:, :] = Q[k:, :] - 2 * np.outer(u, u.T @ Q[k:, :])
        
    return Q.T, R

In [373]:
householder(A)

(array([[-0.43369346,  0.44976826,  0.18146159,  0.4148924 , -0.63604598],
        [-0.61686085, -0.56233206,  0.14735674, -0.47182441, -0.24276133],
        [-0.29907386, -0.33835564, -0.71892615,  0.51919787,  0.09822957],
        [-0.18303336,  0.53814944, -0.59300856, -0.56921039, -0.03513335],
        [-0.55537941,  0.2782118 ,  0.27720701,  0.10807002,  0.72500279]]),
 array([[-1.57317576e+00, -1.47130205e+00, -8.66313237e-01,
         -1.58320899e+00, -1.02602758e+00],
        [ 1.11022302e-16,  3.81370675e-01,  5.23999907e-01,
          5.85116494e-01, -2.12515610e-01],
        [ 5.55111512e-17,  0.00000000e+00, -8.21958487e-01,
         -1.00164134e-01,  4.26562231e-03],
        [ 5.55111512e-17,  0.00000000e+00,  1.66533454e-16,
         -2.32934375e-01,  7.68362949e-02],
        [ 1.11022302e-16,  0.00000000e+00, -5.55111512e-17,
          0.00000000e+00,  1.02412933e-01]]))

In [374]:
scipy.linalg.qr(A)

(array([[-0.43369346,  0.44976826,  0.18146159,  0.4148924 , -0.63604598],
        [-0.61686085, -0.56233206,  0.14735674, -0.47182441, -0.24276133],
        [-0.29907386, -0.33835564, -0.71892615,  0.51919787,  0.09822957],
        [-0.18303336,  0.53814944, -0.59300856, -0.56921039, -0.03513335],
        [-0.55537941,  0.2782118 ,  0.27720701,  0.10807002,  0.72500279]]),
 array([[-1.57317576, -1.47130205, -0.86631324, -1.58320899, -1.02602758],
        [ 0.        ,  0.38137068,  0.52399991,  0.58511649, -0.21251561],
        [ 0.        ,  0.        , -0.82195849, -0.10016413,  0.00426562],
        [ 0.        ,  0.        ,  0.        , -0.23293437,  0.07683629],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.10241293]]))

### Problem 5

In [378]:
def hessenberg(A):
    m, n = A.shape
    H = A.copy()
    Q = np.eye(m)
    
    for k in range(n-3):
        u = H[k+1:, k].copy()
        u[0] = u[0] + sign(u[0]) * norm(u)
        u = u / norm(u)
        H[k+1:, k:] = H[k+1:, k:] - 2 * np.outer(u, u.T @ H[k+1:, k:])
        H[:, k+1:] = H[:, k+1:] - 2 * np.outer(H[:, k+1:] @ u, u)
        Q[k+1:, :] = Q[k+1:, :] - 2 * np.outer(u, u.T @ Q[k+1:, :])
        
    return H, Q.T

In [379]:
hessenberg(A)

(array([[ 6.82276031e-01, -1.07262824e+00, -3.99986658e-01,
          2.73649058e-01, -5.30439957e-01],
        [-1.41752650e+00,  1.97944227e+00,  7.88512967e-01,
         -3.59242906e-01,  4.81151235e-01],
        [ 5.55111512e-17,  5.05518162e-01,  3.90825040e-01,
          3.49312742e-01,  7.87654644e-01],
        [ 0.00000000e+00, -5.55111512e-17, -1.53036553e-01,
          3.04052315e-01, -1.89669749e-01],
        [ 0.00000000e+00,  0.00000000e+00,  4.77079363e-02,
          3.99296431e-01,  8.26259217e-02]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.68459428,  0.52199494,  0.37792816, -0.34062039],
        [ 0.        , -0.33191319, -0.17321939, -0.79386339, -0.47917596],
        [ 0.        , -0.20313105, -0.80538305,  0.45470102, -0.32146991],
        [ 0.        , -0.61636197, -0.22107569, -0.14212042,  0.74231075]]))

In [381]:
scipy.linalg.hessenberg(A, calc_q=True)

(array([[ 0.68227603, -1.07262824, -0.39998666, -0.41911614, -0.4249612 ],
        [-1.4175265 ,  1.97944227,  0.78851297,  0.48616226,  0.35243188],
        [ 0.        ,  0.50551816,  0.39082504, -0.09906548,  0.85592363],
        [ 0.        ,  0.        ,  0.16030045,  0.22487832,  0.14532369],
        [ 0.        ,  0.        ,  0.        , -0.44364249,  0.16179992]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.68459428,  0.52199494, -0.46217662, -0.21270806],
        [ 0.        , -0.33191319, -0.17321939,  0.61527975, -0.69372869],
        [ 0.        , -0.20313105, -0.80538305, -0.52977108, -0.17157656],
        [ 0.        , -0.61636197, -0.22107569,  0.3566037 ,  0.66637622]]))