# QR Decomposition

In [1]:
from scipy.linalg import norm
import numpy as np
import scipy

### Problem 1

In [2]:
def qr(A):
    m, n = A.shape
    Q = A.copy()
    R = np.zeros((n, n))
    
    for i in range(n):
        R[i, i] = norm(Q[:, i])
        Q[:, i] = Q[:, i] / R[i, i]
        for j in range(i + 1, n):
            R[i, j] = Q[:, j].T @ Q[:, i]
            Q[:, j] = Q[:, j] - R[i, j] * Q[:, i]
            
    return Q, R

In [3]:
A = np.random.random((2, 2))

In [4]:
Q, R = qr(A)
Q, R

(array([[ 0.87080802,  0.49162323],
        [ 0.49162323, -0.87080802]]), array([[1.10386976, 0.83548982],
        [0.        , 0.22606326]]))

In [5]:
scipy.linalg.qr(A, mode="economic")

(array([[-0.87080802, -0.49162323],
        [-0.49162323,  0.87080802]]), array([[-1.10386976, -0.83548982],
        [ 0.        , -0.22606326]]))

In [6]:
Q.T @ Q

array([[1.00000000e+00, 5.55111512e-17],
       [5.55111512e-17, 1.00000000e+00]])

In [7]:
Q @ R

array([[0.96125863, 0.83868918],
       [0.54268801, 0.21388851]])

In [8]:
A

array([[0.96125863, 0.83868918],
       [0.54268801, 0.21388851]])

### Problem 2

In [9]:
def det(A):
    return np.diag(qr(A)[1]).prod()

In [10]:
det(A)

0.24954439044260504

In [11]:
scipy.linalg.det(A)

-0.24954439044260507

### Problem 3

In [12]:
def solve(A, b):
    Q, R = qr(A)
    n = R.shape[0]
    y = Q.T @ b
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        subtract = 0
        for j in range(i+1, n):
            subtract += R[i, j] * x[j]
        x[i] = (y[i] - subtract) / R[i, i]
        
    return x

In [13]:
A = np.random.random((5, 5))
A

array([[0.642974  , 0.18609705, 0.8995896 , 0.7174954 , 0.70776199],
       [0.93310894, 0.46324289, 0.54797567, 0.64315527, 0.34475892],
       [0.98534642, 0.92138874, 0.01797173, 0.91513226, 0.55118233],
       [0.43040781, 0.96051496, 0.49174523, 0.07294928, 0.626172  ],
       [0.34021046, 0.05405226, 0.3617909 , 0.76732786, 0.50948027]])

In [14]:
b = np.ones(5)

In [15]:
solve(A, b)

array([-3.63628708,  3.44212966,  3.0531623 ,  3.91404991, -4.03728655])

In [16]:
scipy.linalg.solve(A, b)

array([-3.63628708,  3.44212966,  3.0531623 ,  3.91404991, -4.03728655])

### Problem 4

In [17]:
sign = lambda x: 1 if x >= 0 else -1

def householder(A):
    m, n = A.shape
    R = A.copy()
    Q = np.eye(m)
    
    for k in range(n-1):
        u = R[k:, k].copy()
        u[0] = u[0] + sign(u[0]) * norm(u)
        u = u / norm(u)
        R[k:, k:] = R[k:, k:] - 2 * np.outer(u, u.T @ R[k:, k:])
        Q[k:, :] = Q[k:, :] - 2 * np.outer(u, u.T @ Q[k:, :])
        
    return Q.T, R

In [18]:
householder(A)

(array([[-0.40217233, -0.3668522 ,  0.59181099,  0.04892362, -0.59248892],
        [-0.58364816, -0.28780947, -0.03586012, -0.57822139,  0.49081016],
        [-0.61632206,  0.24331641, -0.62023024,  0.25897384, -0.33044098],
        [-0.26921479,  0.8128406 ,  0.48870946, -0.02246855,  0.16574615],
        [-0.21279746, -0.25034467,  0.15795987,  0.7718123 ,  0.52095993]]),
 array([[-1.59875247e+00, -1.18317317e+00, -9.02064679e-01,
         -1.41087383e+00, -1.10255690e+00],
        [ 2.22044605e-16,  7.89807062e-01, -1.74218126e-01,
         -3.58454548e-01,  1.56675139e-01],
        [ 1.11022302e-16,  0.00000000e+00,  7.99058912e-01,
         -9.17665571e-03,  4.51131890e-01],
        [ 5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
          4.90805673e-01,  3.57175062e-01],
        [ 5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00, -6.30587748e-02]]))

In [19]:
scipy.linalg.qr(A)

(array([[-0.40217233, -0.3668522 ,  0.59181099,  0.04892362, -0.59248892],
        [-0.58364816, -0.28780947, -0.03586012, -0.57822139,  0.49081016],
        [-0.61632206,  0.24331641, -0.62023024,  0.25897384, -0.33044098],
        [-0.26921479,  0.8128406 ,  0.48870946, -0.02246855,  0.16574615],
        [-0.21279746, -0.25034467,  0.15795987,  0.7718123 ,  0.52095993]]),
 array([[-1.59875247, -1.18317317, -0.90206468, -1.41087383, -1.1025569 ],
        [ 0.        ,  0.78980706, -0.17421813, -0.35845455,  0.15667514],
        [ 0.        ,  0.        ,  0.79905891, -0.00917666,  0.45113189],
        [ 0.        ,  0.        ,  0.        ,  0.49080567,  0.35717506],
        [ 0.        ,  0.        ,  0.        ,  0.        , -0.06305877]]))

### Problem 5

In [20]:
def hessenberg(A):
    m, n = A.shape
    H = A.copy()
    Q = np.eye(m)
    
    for k in range(n-3):
        u = H[k+1:, k].copy()
        u[0] = u[0] + sign(u[0]) * norm(u)
        u = u / norm(u)
        H[k+1:, k:] = H[k+1:, k:] - 2 * np.outer(u, u.T @ H[k+1:, k:])
        H[:, k+1:] = H[:, k+1:] - 2 * np.outer(H[:, k+1:] @ u, u)
        Q[k+1:, :] = Q[k+1:, :] - 2 * np.outer(u, u.T @ Q[k+1:, :])
        
    return H, Q.T

In [21]:
hessenberg(A)

(array([[ 6.42974004e-01, -1.09967457e+00,  5.80917903e-01,
          3.17864090e-01,  4.60253057e-01],
        [-1.46376019e+00,  1.73699923e+00, -9.03668552e-01,
          5.29665379e-01, -2.59297001e-03],
        [ 0.00000000e+00, -6.83497773e-01, -1.51496876e-01,
         -2.48264921e-01,  3.35670320e-01],
        [ 0.00000000e+00,  0.00000000e+00, -6.20858257e-02,
         -5.69500950e-01, -1.74279408e-01],
        [-5.55111512e-17,  0.00000000e+00,  6.50890343e-01,
          1.36625560e-01,  4.76427650e-02]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.63747392, -0.25437663, -0.6307057 , -0.36211857],
        [ 0.        , -0.6731611 , -0.25256301,  0.66359362,  0.20666294],
        [ 0.        , -0.29404257,  0.8771964 ,  0.14483935, -0.35083757],
        [ 0.        , -0.23242227,  0.31942281, -0.3753337 ,  0.83849482]]))

In [22]:
scipy.linalg.hessenberg(A, calc_q=True)

(array([[ 0.642974  , -1.09967457,  0.5809179 ,  0.42799065,  0.36013117],
        [-1.46376019,  1.73699923, -0.90366855, -0.05287563,  0.52702591],
        [ 0.        , -0.68349777, -0.15149688,  0.35772761, -0.21526958],
        [ 0.        ,  0.        ,  0.6538447 ,  0.04563758,  0.19530116],
        [ 0.        ,  0.        ,  0.        , -0.1156038 , -0.56749577]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.63747392, -0.25437663, -0.30059369, -0.66224087],
        [ 0.        , -0.6731611 , -0.25256301,  0.14271762,  0.68021889],
        [ 0.        , -0.29404257,  0.8771964 , -0.36300556,  0.11087112],
        [ 0.        , -0.23242227,  0.31942281,  0.87034595, -0.2940185 ]]))