# Math Problem Set 6

Natasha Watkins

In [16]:
import numpy as np
from scipy.linalg import norm
from scipy.optimize import minimize, rosen
import matplotlib.pyplot as plt

### Exercise 9.6

In [2]:
def steepest_descent(x0, b, Q, ɛ=1e-5, maxiter=100):
    
    diff = 1e3
    i = 0
    x = x0
    
    while diff > ɛ and i < maxiter:
        Df = Q @ x - b
        α = np.outer(Df, Df) / (Df @ Q @ Df)
        new_x = x - α @ Df
        diff = norm(new_x - x)
        x = new_x
        i += 1
        
    return x

In [3]:
Q = np.array([[5, 0], 
              [0, 1]])
b = np.array([3, 2])
x = np.array([1, 1])
c = 1

steepest_descent(x, b, Q)

array([0.60000269, 1.99999329])

In [4]:
f = lambda x: 0.5 * x.T @ Q @ x - b.T @ x + c
minimize(f, x)

      fun: -1.8999999999999995
 hess_inv: array([[2.00003922e-01, 3.44462648e-06],
       [3.44462648e-06, 1.00002627e+00]])
      jac: array([ 0.00000000e+00, -2.98023224e-08])
  message: 'Optimization terminated successfully.'
     nfev: 28
      nit: 6
     njev: 7
   status: 0
  success: True
        x: array([0.59999999, 1.99999997])

### Exercise 9.7

In [5]:
def find_gradient(f, x, Rerr=1e-5):
    
    h = np.sqrt(Rerr)
    f0 = f(x)
    
    if np.isscalar(x):
        n = 1
    else:
        n = len(x)
    
    if np.isscalar(f0):
        m = 1
    else:
        m = len(f0)
        
    Df = np.empty((m, n))

    
    for i in range(n):
        Df[:, i] = ((f(x + h * np.eye(n)[:, i]) - f0) - (f(x - h * np.eye(n)[:, i]) - f0)) / (2 * h)
    
    return Df

In [6]:
f = lambda x: np.array([x[0] ** 2 + x[2], x[0] ** 3 - x[1]]).T
x = np.array([1, 2, 3])

find_gradient(f, x)

array([[ 2.     ,  0.     ,  1.     ],
       [ 3.00001, -1.     ,  0.     ]])

### Exercise 9.8

Previous code to compute minimum using secant method...

In [31]:
def secant_method(f, x0, x1, ɛ=1e-6, max_iter=1000):
    
    x = np.zeros(max_iter)  # Store x's
    x[0] = x0
    x[1] = x1
    f_primes = np.zeros(max_iter)  # Store f_primes
    f_primes[0] = find_gradient(f, x0).flatten()
    
    diff = 1e3  # Initialise distance
    i = 1       # Initialise iteration from 1 (x0 already calculated)
    
    while diff > ɛ and i < max_iter:
        f_primes[i] = find_gradient(f, x[i]).flatten()
        x[i+1] = x[i] - f_primes[i] * (x[i] - x[i-1])/(f_primes[i] - f_primes[i-1])  # Update x
        diff = np.abs(x[i] - x[i-1]) / np.abs(x[i])  # Normalised difference
        i += 1
        
    return x[i]

In [45]:
def steepest_descent(f, x0, ɛ=1e-5, maxiter=1000):
    
    diff = 1e3
    i = 0
    x = x0
    
    while diff > ɛ and i < maxiter:
        Df = find_gradient(f, x).flatten()
        ϕ = lambda α: f(x - α * Df.T)
        α = secant_method(ϕ, 0.1, 0.8)
        new_x = x - α * Df
        diff = norm(new_x - x)
        x = new_x
        i += 1
        
    return x

### Exercise 9.9

In [46]:
def f(params):
    x, y = params
    return 100 * (y - x**2)**2 + (1 - x)**2

In [47]:
steepest_descent(f, np.array([-2, 2]))

array([0.9970849 , 0.99416807])

In [41]:
minimize(rosen, [-2, 2])

      fun: 1.8074006428375337e-11
 hess_inv: array([[0.48100066, 0.95987351],
       [0.95987351, 1.92026229]])
      jac: array([-9.52886349e-06,  4.99447910e-06])
  message: 'Optimization terminated successfully.'
     nfev: 168
      nit: 35
     njev: 42
   status: 0
  success: True
        x: array([0.99999575, 0.99999152])